### PR TITLE
Add github workflows for Dockerfile

### PR DESCRIPTION
**Pull request by michal-kowalczyk**
This PR introduces running unit tests for OpenADR-VEN-Library with use of github workflows.

### CODE REVIEW

**Review by cirochang — CHANGES_REQUESTED** [review]
The pipeline seems to be failing on unit test https://github.com/AnalyticsFire/OpenADR-VEN-Library/runs/1710520709?check_suite_focus=true.

**Comment by y3ti** [comment]
I think we can close this pull request. The new version of the workflow is in https://github.com/AnalyticsFire/OpenADR-VEN-Library/pull/4

**Comment by michal-kowalczyk** [comment]
> The pipeline seems to be failing on unit test https://github.com/AnalyticsFire/OpenADR-VEN-Library/runs/1710520709?check_suite_focus=true.

It was intentional to check if we can handle failures.

**Comment by michal-kowalczyk** [comment]
> I think we can close this pull request. The new version of the workflow is in #4

OK, let's close it.

**Pull request closed without merging**
